#!/usr/bin/python3

# Copyright 2025 SUSE LLC
#
# This file is part of ec2imgutils
#
# ec2imgutils is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ec2imgutils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ec2deprecateimg. If not, see <http://www.gnu.org/licenses/>.

import argparse
import os
import sys

import ec2imgutils.ec2utils as utils
import ec2imgutils.ec2disabledeprecationimg as ec2disdepimg
from ec2imgutils.ec2imgutilsExceptions import (
    EC2AccountException,
    EC2DisableDeprecationImgException
)


# ----------------------------------------------------------------------------
def check_required_arguments(args, logger):
    """This function is used to assure the additional requirements over
    arguments (which ones are mandatory, etc.) are met.
    """
    check_disable_deprecation_image_args_present(args, logger)


# ----------------------------------------------------------------------------
def check_disable_deprecation_image_args_present(args, logger):
    """This function checks that at least one of the possible args to specify
    the image to disable deprecation is present
    """
    if (
        not args.image_id and not
        args.image_name
    ):
        error_msg = 'ec2disabledeprecationimg: error: one of the arguments '
        error_msg += '--image-id --image-name is required'
        logger.error(error_msg)
        sys.exit(1)


# ----------------------------------------------------------------------------
def get_config(args, logger):
    """Function to the the configutation parsed from the configuration file
    provided as an argument (or the default path)
    """
    config_file = os.path.expanduser(args.configFilePath)
    config = None
    if not os.path.isfile(config_file):
        logger.error('Configuration file "%s" not found.' % config_file)
        sys.exit(1)
    try:
        config = utils.get_config(config_file)
    except Exception as e:
        logger.exception(e)
        sys.exit(1)
    return config


# ----------------------------------------------------------------------------
def get_access_key(args, config, logger):
    """Function to get the access_key to AWS with the data provided as command
    line args and configuration.
    """
    access_key = args.accessKey
    if not access_key:
        try:
            access_key = utils.get_from_config(
                args.accountName,
                config,
                None,
                'access_key_id',
                '--access-id'
            )
        except EC2AccountException as e:
            logger.error(e)
            sys.exit(1)

    if not access_key:
        logger.error('Could not determine account access key')
        sys.exit(1)
    return access_key


# ----------------------------------------------------------------------------
def get_secret_key(args, config, logger):
    """Function to get the secret_key to AWS with the data provided as command
    line args and configuration.
    """
    secret_key = args.secretKey
    if not secret_key:
        try:
            secret_key = utils.get_from_config(
                args.accountName,
                config,
                None,
                'secret_access_key',
                '--secret-key'
            )
        except EC2AccountException as e:
            logger.error(e)
            sys.exit(1)

    if not secret_key:
        logger.error('Could not determine account secret access key')
        sys.exit(1)
    return secret_key


# ----------------------------------------------------------------------------
def get_image_deprecation_disabler(args, access_key, secret_key, logger):
    """
    Function to get an instance of the ec2imgutils.EC2DisableDeprecationImg
     class
    """
    try:
        undeprecator = ec2disdepimg.EC2DisableDeprecationImg(
            access_key=access_key,
            image_id=args.image_id,
            image_name=args.image_name,
            public_only=args.publicOnly,
            secret_key=secret_key,
            log_callback=logger
        )
    except EC2DisableDeprecationImgException as e:
        logger.error(e)
        sys.exit(1)
    return undeprecator


# ----------------------------------------------------------------------------
def parse_args(args):
    """Command argument parsing function."""
    parser = argparse.ArgumentParser(description='Deprecate images in EC2')
    parser.add_argument(
        '-a', '--account',
        dest='account_name',
        help='Account to use',
        metavar='ACCOUNT_NAME',
    )
    parser.add_argument(
        '--access-id',
        dest='access_key',
        help='AWS access key (Optional)',
        metavar='AWS_ACCESS_KEY'
    )
    help_msg = 'Do not perform any action, print information about actions '
    help_msg += 'that would be performed instared (Optional)'
    parser.add_argument(
        '-n', '--dry-run',
        action='store_true',
        default=False,
        dest='dry_run',
        help=help_msg
    )
    parser.add_argument(
        '-f', '--file',
        default=os.sep.join(['~', '.ec2utils.conf']),
        dest='config_file_path',
        help='Path to configuration file, default ~/.ec2utils.conf (Optional)',
        metavar='CONFIG_FILE'
    )
    # Note, one of the arguments in the group is required if --version is
    # not specified. However setting this behavior through the parser
    # also requiers one argument to be specified even if --version is specified
    # This parser behavior is true even if --version and the group are part of
    # the same subgroup
    undeprecation_image_id = parser.add_mutually_exclusive_group()
    undeprecation_image_id.add_argument(
        '--image-id',
        dest='image_id',
        help='The AMI ID of the image to be undeprecated (Optional)',
        metavar='AMI_ID'
    )
    undeprecation_image_id.add_argument(
        '--image-name',
        dest='image_name',
        help='The image name of the image to be undeprecated (Optional)',
        metavar='IMAGE_NAME'
    )
    parser.add_argument(
        '--public-only',
        action='store_true',
        default=False,
        dest='publicOnly',
        help='Only consider images that are public (Optional)'
    )
    help_msg = 'Comma separated list of regions for publishing, all integrated'
    help_msg += ' regions if not given (Optional)'
    parser.add_argument(
        '-r', '--regions',
        dest='regions',
        help=help_msg,
        metavar='EC2_REGIONS'
    )
    parser.add_argument(
        '-s', '--secret-key',
        dest='secret_key',
        help='AWS secret access key (Optional)',
        metavar='AWS_SECRET_KEY'
    )
    parser.add_argument(
        '--verbose',
        action='store_true',
        default=False,
        dest='verbose',
        help='Enable on verbose output'
    )
    parser.add_argument(
        '--version',
        action='version',
        version=utils.get_version(),
        help='Program version'
    )
    parsed_args = parser.parse_args(args)
    return parsed_args


# ----------------------------------------------------------------------------
def disable_deprecation_images_in_region(
    deprecation_disabler,
    dry_run,
    region,
    errors,
    logger
):
    """Function that deprecates the specified images for a AWS region. The
    function returns the errors dictionary with any error it found added
    """
    try:
        if dry_run:
            logger.info('Dry run, image attributes will not be modified')
            deprecation_disabler.print_disable_deprecation_info()
        else:
            deprecation_disabler.disable_deprecation_for_images()
    except EC2DisableDeprecationImgException as e:
        errors[region] = format(e)
    except Exception as e:
        print_errors(errors, logger)
        logger.exception(e)
        sys.exit(1)
    return errors


# ----------------------------------------------------------------------------
def print_errors(errors, logger):
    """Function that prints the collected errors during image deprecation
    process
    """
    if errors:
        logger.error('Collected errors:')
        for region, error in list(errors.items()):
            logger.error('Region: %s -> %s' % (region, error))


# ----------------------------------------------------------------------------
def main(args):
    args = parse_args(args)
    logger = utils.get_logger(args.verbose)
    check_required_arguments(args, logger)

    config = get_config(args, logger)
    access_key = get_access_key(args, config, logger)
    secret_key = get_secret_key(args, config, logger)

    regions = utils.get_regions(args, access_key, secret_key)
    deprecation_disabler = get_image_deprecation_disabler(
        args,
        access_key,
        secret_key,
        logger
    )

    # Collect all the errors to be displayed later
    errors = {}
    for region in regions:
        deprecation_disabler.set_region(region)
        errors = disable_deprecation_images_in_region(
            deprecation_disabler,
            args.dry_run,
            region,
            errors,
            logger
        )

    if errors:
        print_errors(errors, logger)
        sys.exit(1)


# ----------------------------------------------------------------------------
if __name__ == '__main__':
    main(sys.argv[1:])
